CGsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('GCapp/', include('GCapp.urls')),
    path('admin/', admin.site.urls),
]

GCapp/urls.py
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'GCapp'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name = 'logout'),
    path('main/', views.main, name = 'main'),
    path('<int:collection_gameid>/',views.game, name = 'game'),
    path('news/<int:news_id>/', views.detail, name='detail'),
    path('errors/', views.error, name = 'errors'),
    path('search/', views.search ,name = 'search'),
    path('searchMygame/', views.searchMygame ,name = 'searchMygame'),
    path('delete/', views.delete, name = 'delete'),
    path('add/', views.add, name = 'add'),
    path('community/<int:communityid>/', views.community, name = 'community'),
    path('post/<int:postid>/',views.post,name = 'post'),
    path('profile/', views.profile, name = 'profile'),
    path('edit/',views.edit, name = 'edit'),
    #path('captcha/', include('captcha.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GCapp/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from .models import Game_news
from .models import GameCollection
from .models import Games
from .models import Users
from .models import Comments
from .models import Community
from .models import Posts
from .models import PostComments
from django.template import loader
from django.http import Http404
from . import models
from . import forms
from .forms import CommentForm
from .forms import TypeForm
from .forms import PostCommentForm
import hashlib
import json
import random
import string
import csv
import pandas as pd

#加密算法
def hash_code(s, salt='mysite'):# 加点盐
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


# Create your views here.
'''
Main page
'''
def index(request):
    #将数据存入数据库
    '''
    data = pd.read_csv('./BoardGameData.csv')
    for id, name, intro, score, img in zip(data['id'], data['name'], data['intro'], data['score'], data['img']):
        typeList = ['N/A',
                   'abstract strategy',
                   'action / dexterity',
                   'adventure',
                   'age of reason',
                   'american civil war',
                   'american indian wars',
                   'american revolutionary war',
                   'american west',
                   'ancient',
                   'animals',
                   'arabian',
                   'aviation / flight',
                   'bluffing',
                   'book',
                   'card game',
                   "children's game",
                   'city building',
                   'civil war',
                   'civilization',
                   'collectible components',
                   'comic book / strip',
                   'deduction',
                   'dice',
                   'economic',
                   'educational',
                   'electronic',
                   'environmental',
                   'expansion for base-game',
                   'exploration',
                   'fan expansion',
                   'fantasy',
                   'farming',
                   'fighting',
                   'game system',
                   'horror',
                   'humor',
                   'industry / manufacturing',
                   'korean war',
                   'mafia',
                   'math',
                   'mature / adult',
                   'maze',
                   'medical',
                   'medieval',
                   'memory',
                   'miniatures',
                   'modern warfare',
                   'movies / tv / radio theme',
                   'murder/mystery',
                   'music',
                   'mythology',
                   'napoleonic',
                   'nautical',
                   'negotiation',
                   'novel-based',
                   'number',
                   'party game',
                   'pike and shot',
                   'pirates',
                   'political',
                   'post-napoleonic',
                   'prehistoric',
                   'print & play',
                   'puzzle',
                   'racing',
                   'real-time',
                   'religious',
                   'renaissance',
                   'science fiction',
                   'space exploration',
                   'spies/secret agents',
                   'sports',
                   'territory building',
                   'trains',
                   'transportation',
                   'travel',
                   'trivia',
                   'video game theme',
                   'vietnam war',
                   'wargame',
                   'word game',
                   'world war i',
                   'world war ii',
                   'zombies'
                   ]
        models.Games(
            game_id=id,
            game_name=name,
            game_introduction=intro,
            game_score=score,
            game_image=img,
            game_type=random.choice(typeList)
        ).save()

    '''
    '''
    录入用户信息
    '''
    '''
    # name list
    nameList = [
        'EMMA',
        'MIA',
        'OLIVIA',
        'SOPHIA',
        'ISABELLA',
        'EMILY',
        'CAMILA',
        'SOFIA',
        'AVA',
        'ABIGAIL',
        'VICTORIA',
        'CHARLOTTE',
        'EVELYN',
        'LUNA',
        'SCARLETT',
        'PENELOPE',
        'AMELIA',
        'ARIA',
        'MILA',
        'ELIZABETH',
        'CHLOE',
        'ZOE',
        'GRACE',
        'SAMANTHA',
        'GENESIS',
        'ALEXA',
        'MADISON',
        'ELLA',
        'AVERY',
        'LEAH',
        'AUDREY',
        'NATALIE',
        'MELANIE',
        'MAYA',
        'BELLA',
        'ZOEY',
        'LAYLA',
        'HARPER',
        'XIMENA',
        'RILEY',
        'LILY',
        'HANNAH',
        'AALIYAH',
        'VIOLET',
        'DELILAH',
        'VALENTINA',
        'AUBREY',
        'ELENA',
        'ARIANA',
        'ALLISON',
        'ELLIE',
        'NATALIA',
        'STELLA',
        'AURORA',
        'HAZEL',
        'ALICE',
        'HAILEY',
        'GIANNA',
        'ANDREA',
        'EMILIA',
        'LEILANI',
        'EVA',
        'SAVANNAH',
        'ADELINE',
        'BROOKLYN',
        'ARIANNA',
        'VALERIA',
        'CLAIRE',
        'ELIANA',
        'SARAH',
        'NAOMI',
        'VALERIE',
        'RUBY',
        'ELEANOR',
        'ATHENA',
        'JADE',
        'KAYLA',
        'MARIA',
        'ALINA',
        'KAYLEE',
        'ARIEL',
        'KATHERINE',
        'LUCY',
        'KIMBERLY',
        'MELODY',
        'JASMINE',
        'ALYSSA',
        'LILIANA',
        'ASHLEY',
        'SOPHIE',
        'ANNA',
        'BRIANNA',
        'ADDISON',
        'EVERLY',
        'ISLA',
        'ALEXANDRA',
        'LILLIAN',
        'ISABEL',
        'DANIELA',
        'MADELINE',
        'MADELYN',
        'IVY',
        'NORA',
        'JULIA',
        'KENNEDY',
        'DAISY',
        'DALEYZA',
        'ISABELLE',
        'NEVAEH',
        'ARYA',
        'ANGELA',
        'QUINN',
        'ALIYAH',
        'IRIS',
        'GISELLE',
        'JOCELYN',
        'NICOLE',
        'JULIANA',
        'MICHELLE',
        'JULIETTE',
        'LEILA',
        'AUTUMN',
        'ANGELINA',
        'LUCIA',
        'VIVIAN',
        'GABRIELLA',
        'ROSE',
        'SKYLAR',
        'CORA',
        'KYLIE',
        'DIANA',
        'KAMILA',
        'ANA',
        'AMAYA',
        'SADIE',
        'BRIELLE',
        'FAITH',
        'VANESSA',
        'MELISSA',
        'SERENITY',
        'MACKENZIE',
        'JESSICA',
        'JULIANNA',
        'EMERY',
        'AUBREE',
        'SELENA',
        'SIENNA',
        'REAGAN',
        'ESMERALDA',
        'NOVA',
        'TAYLOR',
        'JAYLEEN',
        'JOSEPHINE',
        'STEPHANIE',
        'ARABELLA',
        'CAROLINE',
        'PAISLEY',
        'BAILEY',
        'YARETZI',
        'ALESSANDRA',
        'LEIA',
        'CLARA',
        'DESTINY',
        'SARA',
        'JACQUELINE',
        'JULIET',
        'KINSLEY',
        'LYLA',
        'RYLEE',
        'PEYTON',
        'ALEXIS',
        'ANNABELLE',
        'MIRANDA',
        'WILLOW',
        'GENEVIEVE',
        'JENNIFER',
        'SYDNEY',
        'JIMENA',
        'LAUREN',
        'ALONDRA',
        'CATALINA',
        'ELISE',
        'PIPER',
        'FATIMA',
        'GABRIELA',
        'KAIA',
        'ALANA',
        'CATHERINE',
        'SUMMER',
        'JOANNA',
        'AMANDA',
        'ITZEL',
        'FIONA',
        'ANASTASIA',
        'IZABELLA',
        'ALICIA',
        'CECILIA',
        'NORAH',
        'ADALYN',
        'ADALYNN',
        'LYDIA',
        'ADRIANA',
        'CHARLIE',
        'OLIVE',
        'CAMILLA',
        'LIA',
        'PAIGE',
        'DANIELLA',
        'MALIA',
        'RACHEL',
        'RENATA',
        'VIVIENNE',
        'MAKAYLA',
        'REBECCA',
        'REESE',
        'ELOISE',
        'FERNANDA',
        'MARIAH',
        'MARY',
        'JULIETA',
        'EDEN',
        'MARIANA',
        'ADALINE',
        'AYLA',
        'SIERRA',
        'ALISON',
        'ESTHER',
        'JORDYN',
        'JUNE',
        'PRESLEY',
        'VIVIANA',
        'AYLIN',
        'DAHLIA',
        'SAGE',
        'ADELYN',
        'APRIL',
        'ELIZA',
        'SAMARA',
        'HARLEY',
        'KIARA',
        'MYA',
        'SLOANE',
        'AMBER',
        'NOELLE',
        'ANNIE',
        'KHLOE',
        'LAILA',
        'KEIRA',
        'KIRA',
        'REGINA',
        'ELISA',
        'PHOEBE',
        'ZARA',
        'JAYLENE',
        'LILA',
        'LILLY',
        'IVANNA',
        'JAYLA',
        'AMARA',
        'JOY',
        'EVANGELINE',
        'CELESTE',
        'BROOKE',
        'CAMILLE',
        'JULISSA',
        'ALEJANDRA',
        'ARIELLE',
        'CELINE',
        'IRENE',
        'JANE',
        'LONDON',
        'GUADALUPE',
        'JAZMIN',
        'PARKER',
        'ALEXIA',
        'MARGARET',
        'SERENA',
        'DYLAN',
        'GEMMA',
        'LANA',
        'LUCIANA',
        'TEAGAN',
        'FRIDA',
        'LESLIE',
        'NAYELI',
        'NINA',
        'AILEEN',
        'ARIELLA',
        'GALILEA',
        'KATE',
        'KARLA',
        'ROSALIE',
        'TIFFANY',
        'CHELSEA',
        'MELANY',
        'TRINITY',
        'DANIELLE',
        'ELLIANA',
        'MARLEY',
        'BLAKE',
        'ANAHI',
        'CATALEYA',
        'JAYLAH',
        'RUTH',
        'LOLA',
        'MADELEINE',
        'PRISCILLA',
        'ADELINA',
        'JUNIPER',
        'LILAH',
        'CALI',
        'GRACIE',
        'LEXI',
        'DAKOTA',
        'EMERSON',

GCapp/templates/GCapp/community.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>community</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'GCapp/css/main.css' %}" rel="stylesheet"/>
</head>
<body>
<div id="wholebox">
{% if user_id %}
<h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection <a style="color: white;margin-left:70%;font-size: 15px " href='{% url 'GCapp:index' %}'>Main page</a> |  <a style="color: white;font-size: 15px " href='{% url 'GCapp:main' %}'>My page</a></h1>
{% else %}
<h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection <a style="color: white;margin-left:70%;font-size: 15px " href='{% url 'GCapp:login' %}'>Login</a> | <a style="color: white;font-size: 15px " href='{% url 'GCapp:index' %}'>Main page</a></h1>
{% endif %}
    <h2 style="color: black; font-style: italic; margin-top: 50px; margin-left: 30px">{{ community.community_name }}</h2>

{% if post_list %}
    <ul>
    {% for post in post_list %}
        <li><a style="color: lavenderblush" href="{% url 'GCapp:post' post.post_id %}">{{ post.post_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No post in this community</p>
{% endif %}
</div>
</body>
</html>

GCapp/templates/GCapp/errors.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Error</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'GCapp/css/main.css' %}" rel="stylesheet"/>
</head>
<body>
<div id="wholebox">
        <h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection</h1>
<p style="margin-left: 50px; color: lavenderblush; font: italic">
    An error occurs, please check your operation!
</p>
</div>
</body>
</html>

GCapp/templates/GCapp/game.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Game detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'GCapp/css/main.css' %}" rel="stylesheet"/>
</head>
<body>
<div id="wholebox">
{% if request.session.user_name %}
    <h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection<a style="color: white;margin-left:65%;font-size: 15px" href='{% url 'GCapp:logout' %}'>Logout</a> | <a style="color: white;font-size: 15px" href='{% url 'GCapp:profile' %}'>View my profile</a></h1>
<div id="content" style="margin-left: 50px; margin-top: 20px">
    <h2 style="color: black; font-style: italic ;font-weight: bold">{{ game.game_name }}&nbsp;&nbsp;&nbsp;&nbsp;{{ game.game_score}}</h2>

    <button style="background-color: #6f0124" type="submit" class="btn btn-primary float-right" onclick="addcollection({{ game.game_id }});">Add to my collection</button>

{% else %}
    <h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection</h1>
    <div id="content" style="margin-left: 50px; margin-top: 20px">
    <h2 style="color: black; font-style: italic ">{{ game.game_name }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ game.game_score}}</h2>
    <h5 style="color: cornsilk">You haven't login to GameCollection! Please login to add game to your game collection!</h5>
{% endif %}

<a style="color: lavenderblush; margin-left: 20px;" href="{% url 'GCapp:main' %}">View my collection</a>

<a style="color: lavenderblush; margin-left: 20px;" href="{% url 'GCapp:index' %}">Return to index page</a>

<p style="margin-top: 30px"><img width = 400px height = auto src="{% static 'GCapp/media/gameImg/' %}{{game.game_image}}"><br></p>
<h3>Game Introduction</h3>
<p>
    {{ game.game_introduction }}
</p>
<h3>Game Type</h3>
<p>
    {{ game.game_type }}
</p>
<h3>Game Purchase</h3>
<br>
{% if game.game_Amazon %}
    {% if game.game_Ebay %}
    <img width = 40px height = auto src="{% static 'GCapp/image/amazon.png' %}"><a style="color: white;margin-left:10px;font-size: 15px" href={{game.game_Amazon}}>Amazon.com</a>
    <br>
        <img width = 40px height = auto src="{% static 'GCapp/image/ebay.png' %}"><a style="color: white;margin-left:10px;font-size: 15px" href={{game.game_Ebay}}>Ebay.com</a>
    {% else %}
        <img width = 40px height = auto src="{% static 'GCapp/image/amazon.png' %}"><a style="color: white;margin-left:10px;font-size: 15px" href={{game.game_Amazon}}>Amazon.com</a>
        <br>
        <img width = 40px height = auto src="{% static 'GCapp/image/ebay.png' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Product is unavailable on Ebay currently!
    {% endif %}
{% else %}
    {% if game.game_Ebay %}
    <img width = 40px height = auto src="{% static 'GCapp/image/amazon.png' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Product is unavailable on Amazon currently!
    <br>
        <img width = 40px height = auto src="{% static 'GCapp/image/ebay.png' %}"><a style="color: white;margin-left:10px;font-size: 15px" href={{game.game_Ebay}}>Ebay.com</a>
    {% else %}
        <img width = 40px height = auto src="{% static 'GCapp/image/amazon.png' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Product is unavailable on Amazon currently!
    <br>
        <img width = 40px height = auto src="{% static 'GCapp/image/ebay.png' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Product is unavailable on Ebay currently!
    {% endif %}
{% endif %}
</p>


<form action="{% url 'GCapp:game' game.pk %}" method="post" class="comment-form">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-12">
      <label for="{{ form.comment_text.id_for_label }}"> Publish my comment:</label><br>
<input type="text" style="width:500px; height:120px;" name="comment_text">
<br>
      {{ form.text }}
      {{ form.text.errors }}
      <button style="background-color: #6f0124; color: white" type="submit" class="comment-btn">submit</button>
    </div>
  </div>    <!-- row -->
</form>

<ul class="comment-list list-unstyled">
  {% for comment in comment_list %}
  <li class="comment-item">
    <span class="nickname">{{ comment.comment_publisher }}</span>
    <time class="submit-date">{{ comment.comment_date }}</time>
    <div class="text">
      {{ comment.comment_text }}
    </div>
  </li>
  {% empty %}
  There is no comment available currently.
  {% endfor %}
</ul>

</div>
</div>
</div>
</body>

<script type="text/javascript" src="{% static 'GCapp/js/add.js' %}"></script>
<script type="text/javascript" src="{% static 'GCapp/js/jquery-1.11.3.min.js' %}"></script>
<script>
    $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
</script>

</html>

GCapp/templates/GCapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Main page</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'GCapp/css/index.css' %}" rel="stylesheet"/>
</head>
<body >

<div id="wholebox">
{% if user_id %}
<h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection <a style="color: white;margin-left:75%;font-size: 15px " href='{% url 'GCapp:main' %}'>Go to my page</a></h1>
{% else %}
<h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection <a style="color: white;margin-left:75%;font-size: 15px " href='{% url 'GCapp:login' %}'>Login</a></h1>
{% endif %}
<form method="post" action="/GCapp/search/">{% csrf_token %}
    <div id="search">
  <input style="width: 350px; float: left" type="search" class = form-control id = 'gamename' name = 'gamename' placeholder="Search for games" required><button style="margin-top: 5px" type="submit">Search</button>
 </div>
</form>

<div id="community">
<h2 >WALK THROUGH COMMUNITY</h2>
{% if community_list %}
    <ul>
    {% for community in community_list %}
        <li style="padding-top: 20px;"><a style="color: lavenderblush" href="{% url 'GCapp:community' community.community_id %}">{{ community.community_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No community is available.</p>
{% endif %}
</div>

<div id="gamenews">
<h2>RECENT GAME NEWS</h2>
{% if latest_news_list %}
    <ul>
    {% for news in latest_news_list %}
        <li style="margin-left: 50px;padding-top: 15px;" ><a style="color: lavenderblush ;font-size: 15px" href="{% url 'GCapp:detail' news.news_id %}">{{ news.news_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No news is available.</p>
{% endif %}
</div>

<div id="gamesuggestion">
<h2>GAMES RECOMMEND FOR YOU</h2>
{% if recommend_game_list %}
    <ul style="margin-left: 30px; list-style: none;">
    {% for game in recommend_game_list %}
        <li style="display: block;width: fit-content; height: auto; float: left;margin-left: 30px; text-align: center;"><a style="color: lavenderblush;font-size: 15px;font-style: inherit;"href="{% url 'GCapp:game' game.game_id%}">{{ game.game_name}}</a>
            <p><img width = 270px height = 190px src="{% static 'GCapp/media/gameImg/' %}{{game.game_image}}"><br></p>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No game recommendation is available.</p>
{% endif %}
</div>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>


</div>
</body>
</html>

GCapp/templates/GCapp/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Main page</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'GCapp/css/main.css' %}" rel="stylesheet"/>
</head>
<body>
<div id="wholebox">
    <h1 style="color:white"><img width = 40px height = auto src="{% static 'GCapp/image/logo.png' %}">GameCollection<a style="color: white;margin-left:50%;font-size: 15px" href='{% url 'GCapp:logout' %}'>Logout</a> | <a style="color: white;font-size: 15px" href='{% url 'GCapp:profile' %}'>View my profile</a> | <a style="color: white;font-size: 15px" href='{% url 'GCapp:index' %}'>Main page</a> | <a style="color: white;font-size: 15px" href='{% url 'GCapp:edit' %}'>Change my community</a></h1>
    {% if request.session.user_name %}
    <h4 style="color: white; padding-top: 10px;float: left;margin-left: 20px;">{{ request.session.user_name }}! Login successful!</h4>
{% else %}
    <h4 style="color: white;padding-top: 10px; float: left;margin-left: 20px;">You haven't login to GameCollection! Please login to view your game collection!</h4>>
    {% endif %}


<form method="post" action="/GCapp/search/">
  {% csrf_token %}
    <div id="search">
  <input style="width: 350px; float: left" type="search" class = form-control id = 'gamename' name = 'gamename' placeholder="Search for games" required>
  <button type="submit">Search</button>
    </div>
</form>


<div id="collection" style="margin-left: 40px">
<h2 style="color: black; font-style: italic ">My game collection</h2>
  <form method="post" action="/GCapp/searchMygame/" style="float: left">
    {% csrf_token %}
   <input style="width: 150px; height: 25px;float: left" type="searchMygame" class = form-control id = 'gamename' name = 'gamename' placeholder="Input game name" required>
      <button style="background-color:aliceblue; color: black;" type="submit">Search by name</button>
 </form>
<form method="post" action="/GCapp/main/" style="margin-outside: 20px">{% csrf_token %}
    <select style="width: 150px; height: 25px" name="type">
        {# 这里我们遍历form表单中的type这个字典,然后把key,value成对取出  #}
        {% for key,value in type_form.type_choice %}
            <option value="{{ value }}">{{ key }}</option>
        {% endfor %}
    </select>
    <input style="color: black; background-color: aliceblue" type="submit" value="Search by type"/>
    {% csrf_token %}
</form>



{% if game_collection_list %}
    <ul>
    {% for game in game_collection_list %}
        <li style="padding-top: 20px;"><a style="color: lavenderblush" href="{% url 'GCapp:game' game.collection_gameid.game_id %}">{{ game.collection_gameid.game_name }}</a>
        <button style="height: 18px; width: auto;line-height: 10px;margin: 0px;border: 0px; background-color: lightgrey; color: black;text-align: center" type="submit" class="btn btn-primary float-right" onclick="deletecollection({{ game.collection_gameid.game_id }});">Delete</button></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No game in your collection.</p>
{% endif %}

<h2 style="color: black; font-style: italic">Games belong to this type</h2>
{% if filtered_game_list %}
    <ul>
    {% for game in filtered_game_list %}
        <li><a style="color: white" href="{% url 'GCapp:game' game.collection_gameid.game_id%}">{{ game.collection_gameid.game_name }}</a></li>
        <button style="height: 25px; width: auto; background-color: #6f0124; color: white;" type="submit" class="btn btn-primary float-right" onclick="deletecollection({{ game.collection_gameid.game_id }});">Delete</button>
    {% endfor %}
    </ul>
{% else %}
    <p>No game belong to this type</p>
{% endif %}

<h2 style="color: black; font-style: italic" >Game suggested according to your tag</h2>
{% if recommend_game_list %}
    <ul>
    {% for game in recommend_game_list %}
        <li><a style="color: white" href="{% url 'GCapp:game' game.game_id %}">{{ game.game_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No game recommendation</p>
{% endif %}

</div>
</div>
</body>
<script type="text/javascript" src="{% static 'GCapp/js/delete.js' %}"></script>
<script type="text/javascript" src="{% static 'GCapp/js/jquery-1.11.3.min.js' %}"></script>
<script>
    $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
</script>
</html>